#!/usr/bin/env bash
# configuring web-01 to have an HTTP response header

# Updating packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index page
echo "hello world!" | sudo tee /var/www/html/index.html

# Performing a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Mashudu14 permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a cutom error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Custom HTTP header

sude sed -i "/server_name _;/a add_header X-server-By $HOSTNAME;" /etc/nginx/sites/default

# test for syntax errors
sudo nginx -t

# Restart the config files
sudo service nginx restart
